#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop
# On the 9th iteration, displays "Hi" before "Best School".

COUNTER=0

while [ $COUNTER -lt 11 ]
do
	 if [ $COUNTER = 9 ]
	 then
		 echo "Hi"
	 else
		 echo "Best School"
	 fi
	 let COUNTER+=1
done
